import os

BASE = r"C:\Users\danie\milpaytools\src\content\blog"

paragraphs = {
"oconus-cola-trap": "OCONUS COLA is a cost-of-living adjustment designed to equalize purchasing power when overseas duty station costs exceed the U.S. average — not a bonus. Members stationed in Japan, Korea, Germany, and Italy typically receive $400–$1,500/month in OCONUS COLA depending on pay grade and location; spending it means you have only broken even against the higher cost of living, not built any financial advantage. The members who build wealth overseas treat the allowance as invisible in their personal budget and save or invest the difference.",

"crdp-vs-crsc-military-retirement": "Eligible military retirees with VA disability ratings can receive both their full retirement pay and VA disability compensation concurrently through CRDP — or receive tax-free CRSC instead — but not both simultaneously. CRDP (Concurrent Retirement and Disability Pay) is applied automatically for retirees with 20+ years of service and a 50%+ VA rating; CRSC (Combat-Related Special Compensation) must be applied for separately and only covers the portion of disability documented as combat-related. The right choice depends on tax bracket and how much of the disability rating qualifies as combat-related — and the after-tax difference can exceed $400/month.",

"2026-military-pay-raise-explained": "The FY2026 pay raise is 3.8%, effective January 1, 2026 — the largest increase since the 5.2% raise in 2024. In dollar terms, that is approximately $150/month more for an E-5 with 6 years of service, $214/month more for an E-7 with 14 years, and $283/month more for an O-3 with 6 years. BAH also increased approximately 4.2% on average, and Family Separation Allowance rose to $300/month for the first time since 2002 — so the total compensation increase is larger than base pay alone reflects.",

"va-disability-math-explained": "The VA does not add disability percentages together — it uses a whole-person formula (38 CFR § 4.25) where each additional rating is applied to the remaining healthy capacity, not the original 100%. That is why 50% + 30% equals 65% combined, which rounds to 70%, not 80%. Understanding this math before filing additional claims helps identify which conditions will actually push a combined rating to the next compensation tier, which can mean hundreds of dollars per month in the difference.",

"vre-chapter-31-vs-gi-bill": "VR&E (Chapter 31, Veteran Readiness and Employment) covers all tuition and fees with no annual cap, pays the same monthly housing allowance as the GI Bill, and does not reduce GI Bill months — it is a separate, independent benefit. Eligibility requires a service-connected disability rating of 10% or higher, an employment barrier related to that disability, and a discharge under conditions other than dishonorable. For qualifying veterans, using VR&E for an undergraduate degree preserves GI Bill months for graduate school, a career change, or transfer to dependents — making it one of the most valuable and most overlooked benefits in the VA system.",

"tricare-costs-2026-vs-civilian": "Active-duty TRICARE Prime costs $0 — no premiums, no enrollment fees, and no deductibles for care at military treatment facilities — while comparable civilian family health coverage runs $600–$2,000/month in premiums plus $3,000–$6,000 in annual deductibles. For a military family, the healthcare benefit alone represents $15,000–$25,000 per year in civilian equivalent savings. When comparing a military paycheck to a civilian job offer, counting TRICARE at $0 can close or reverse what appears to be a civilian pay advantage.",

"gi-bill-vs-tuition-assistance": "The core principle is straightforward: use Tuition Assistance while on active duty, and save the GI Bill for after separation. Tuition Assistance covers up to $250 per credit hour and $4,500 per fiscal year with no housing component, while the GI Bill's monthly housing allowance — approximately $2,522 nationally for 2025–2026 — is only paid when not receiving active-duty BAH, making it worth nothing while still serving. Using GI Bill months on active duty burns a finite entitlement while leaving the most valuable part of the benefit uncollected.",

"what-civilian-salary-do-i-need": "Translating military compensation to a civilian salary equivalent requires accounting for BAH, BAS, healthcare, and the tax treatment of allowances — not just base pay. An E-6 with 10 years of service at a mid-range duty station may have total compensation worth $87,000–$100,000 per year when allowances and tax advantages are included, which requires a civilian offer of $95,000–$130,000 or more to match depending on location and benefits. Running this calculation before any offer negotiation establishes a concrete floor, not just a feeling.",

"best-worst-bah-duty-stations-2026": "The best BAH duty station is not the one with the highest dollar rate — it is the one where BAH most exceeds actual local housing costs, leaving the largest monthly surplus. In 2026, E-5 with-dependent BAH ranges from $1,584/month at Camp Lejeune to $3,975/month in San Diego, but a high BAH rate in a high-cost market does not necessarily mean more money left over. The installations where BAH goes furthest tend to be mid-cost markets in the South and Midwest where BAH covers local median rents with hundreds of dollars to spare.",

"dual-military-bah-guide": "When two active-duty members are stationed at the same duty station, only one can receive the with-dependents BAH rate — and the correct choice is not automatically the higher-ranking member. The right choice is whichever member has the larger gap between their with-dependents and without-dependents rate at that specific installation, which varies by rank and location in ways that cannot be predicted without checking the actual 2026 DTMO rate tables. Getting this wrong produces a permanent monthly loss that most dual-military couples never revisit after the initial assignment.",

"how-much-does-an-e5-really-make-2026": "E-5 base pay for 4–6 years of service is $3,946.80/month in 2026, but that figure understates actual compensation significantly. Adding BAH (ranging from $1,806/month at Fort Bragg to $3,975/month in San Diego), BAS ($476.95/month), and the tax advantage of those allowances being excluded from federal taxable income, total compensation ranges from approximately $74,000 to $101,000 per year — equivalent to $82,000–$116,000 in civilian pretax salary depending on duty station.",

"pcs-that-costs-14000-vs-makes-6000": "The same PCS move — same rank, same family size, same route — can cost one family $14,000 or generate $6,000 for another, a $20,000 swing that comes entirely from knowing or not knowing entitlements before orders drop. PPM strategy, TLE use, lease timing, and understanding the BAH difference at the gaining station are the variables that drive the outcome. Most of the money left on the table is not recoverable after the move has started — the planning window is before orders are cut.",

"how-to-read-your-military-les": "Your LES (Leave and Earnings Statement) is your military pay stub, available every pay period through myPay at mypay.dfas.mil, and it is the authoritative record of your military pay, deductions, and leave balance. The Entitlements column shows everything you earn — base pay, BAH, BAS, and any special pays — while Deductions shows what comes out, including federal taxes, SGLI, and TSP contributions. A five-minute review each pay period is one of the highest-return financial habits in the military, because errors in dependency status or TSP contributions can cost hundreds of dollars per month and go undetected indefinitely.",

"dual-military-financial-strategies": "Dual active-duty couples receive two salaries, two TSP accounts with combined contribution room of up to $49,000 per year, and the potential for two military pensions — but BAH co-location rules, coordinated orders, and childcare costs require deliberate management. When co-located, only one member receives the with-dependents BAH rate; when stationed separately, both may receive their own BAH, which can significantly exceed combined housing costs. The upside is substantial, but it requires actively managing dependent designation, TSP elections, and joint-spouse assignment preferences at every PCS cycle.",

"file-va-disability-before-separation": "Filing a VA disability claim through the Benefits Delivery at Discharge (BDD) program — 90 to 180 days before separation — produces faster decisions and better-documented outcomes than waiting until after leaving active duty. Active-duty medical records are more complete and easier to access now than they will be years later, and an earlier filing date can minimize the gap between the last military paycheck and the start of tax-free VA disability compensation. At 2026 rates, a 10% rating adds $180.42/month for life — a lifetime value that makes early filing one of the highest-return actions available before separation.",

"sgli-vgli-private-life-insurance": "SGLI provides $500,000 of guaranteed-issue life insurance for $26/month — available to all active-duty members regardless of health or occupation — but it terminates 120 days after separation with no grace period for finding a replacement. VGLI (the government conversion option) is also guaranteed-issue within 240 days of separation, but premiums escalate steeply with age and reach $425+/month by the early 60s. The optimal strategy for most members with dependents is to purchase competitive private term life insurance while still on active duty, 12–24 months before anticipated separation, when health underwriting is most favorable.",

"post-911-gi-bill-explained-2026": "The Post-9/11 GI Bill (Chapter 33) pays tuition and fees, a monthly housing allowance, and a books and supplies stipend to eligible veterans and service members. At 100% eligibility — generally 36+ months of qualifying active duty after September 10, 2001 — it covers 100% of in-state public tuition or up to $30,908.34 per year at private schools, plus a monthly housing allowance equal to E-5 with-dependents BAH at the school's ZIP code, averaging approximately $2,522/month nationally for 2025–2026. Online-only students receive approximately $1,261/month regardless of location, which is one of the most financially consequential distinctions in the program.",

"va-gi-bill-comparison-tool-guide": "The VA GI Bill Comparison Tool at va.gov/education/gi-bill-comparison-tool shows tuition coverage estimates, monthly housing allowance, and Yellow Ribbon status for approved programs — but it does not calculate the benefit percentage for those who served less than 36 months, does not compare GI Bill to VR&E or Tuition Assistance, and does not show state veteran education benefits. The housing allowance displayed is E-5 with-dependents BAH at the school's ZIP code for in-person students, and a flat $1,261/month for online-only enrollment — a difference that can total tens of thousands of dollars over a full degree. Using the tool as a starting point alongside MilPayTools' Education Benefits Calculator gives a more complete comparison.",

"savings-deposit-program-sdp-explained": "The Savings Deposit Program (SDP) pays 10% annual interest — guaranteed by the U.S. government — on up to $10,000 deposited while deployed to a qualifying combat zone for 30 or more consecutive days. A $10,000 deposit at the start of a 9-month deployment earns approximately $750 in guaranteed interest with no market risk. SDP works best as part of a deployment savings stack alongside Roth TSP contributions, not as a replacement for retirement investing.",

"the-47000-gap-bah-duty-station": "Two E-5s with identical rank and years of service earn the same base pay — $4,110/month in 2026 — but their total compensation can differ by nearly $47,000 per year because of BAH variation across duty stations. E-5 with-dependent BAH ranges from $1,260/month at Fort Sill to $3,726/month in Honolulu, and because BAH is excluded from federal taxable income, the civilian salary equivalent of that difference is even larger than the raw numbers suggest. Understanding total compensation at any assignment — not just base pay — can be worth more than a bonus or early promotion in the career decisions that follow.",

"gi-bill-housing-allowance-zip-code": "The GI Bill's monthly housing allowance equals E-5 with-dependents BAH at the school's ZIP code — not the student's home address, and not a fixed national average. In 2026, that means MHA ranges from under $1,200/month at rural schools to over $4,000/month at schools in high-cost urban markets, making school location one of the most significant financial variables in using the GI Bill. Online-only students receive approximately $1,261/month regardless of location, which is why taking even a single in-person class — if feasible — can significantly increase the monthly housing allowance.",

"military-credit-card-scra-mla-benefits": "Active-duty service members qualify for SCRA (Servicemembers Civil Relief Act) protections that cap interest on pre-service debt at 6%, and most major card issuers voluntarily waive annual fees on premium travel cards for active-duty members — a benefit worth $1,000–$3,000+ per year in avoided fees and travel credits. These benefits are real but not automatic: claiming them requires notifying lenders of military status, verifying which cards and accounts are covered at each issuer, and enrolling before separation since most protections end shortly after leaving active duty. Spouse coverage may also be available at some issuers depending on their specific military benefits policy.",

"va-math-costs-you-money": "VA disability ratings are not added together — the combined ratings formula applies each additional percentage to the remaining healthy capacity, not the original 100%. That is why 50% + 30% + 20% produces a 70% combined rating under VA math, not 100%. Understanding where a combined rating sits in the compensation table before filing additional claims helps identify which conditions would actually move it to the next tier — a distinction that can mean several hundred dollars per month in the difference.",

"scra-mla-protections-new-service-members": "SCRA (Servicemembers Civil Relief Act) caps interest rates at 6% on debt held before entering active duty — credit cards, auto loans, student loans, and mortgages — while MLA (Military Lending Act) caps the Military Annual Percentage Rate at 36% on new consumer loans taken out during service. Both laws are automatic by statute, but claiming SCRA's interest rate reduction typically requires written notification to lenders with a copy of orders. Together these protections can save hundreds of dollars per year in interest that would otherwise drain junior enlisted pay — but only if service members know to claim them.",

"bah-rates-2026-complete-guide": "BAH rates increased an average of 4.2% in 2026, effective January 1, and are set by three factors: duty station ZIP code, pay grade, and whether the member has dependents. The allowance is excluded from federal income tax, FICA, and most state income taxes — making each dollar of BAH worth significantly more than equivalent gross wages. In 2026, E-5 with-dependent BAH ranges from approximately $1,584/month at Camp Lejeune to $3,975/month in San Diego, a spread of over $28,000 per year that makes duty station selection one of the largest financial variables in a military career.",

"should-i-stay-to-20-years-military": "Reaching 20 years of active duty unlocks an immediate pension — for an E-7 under High-3, approximately $3,059/month beginning at retirement, typically around age 38–40, with annual cost-of-living adjustments for life. There is no partial vesting at 10, 12, or 15 years under regular longevity retirement: every year short of 20 produces $0 pension rather than a reduced one, which is why the gap between 19 years and 20 years is one of the largest financial cliffs in any compensation system. The math strongly favors reaching 20 for most members in the twelve-to-nineteen-year window, but it cannot capture personal circumstances, quality of life, or post-service career trajectory — those inputs belong to the individual making the decision.",

"what-walking-away-at-12-years-costs": "An E-7 who reaches 20 years locks in approximately $3,071/month in pension for life — while an E-7 who separates at 12 years receives $0 pension under regular longevity retirement. Walking away also means forfeiting TRICARE retiree healthcare (worth $15,000–$25,000/year for a family) and 8 more years of government TSP matching. To replace the pension, healthcare, and TSP matching of a 20-year military retirement in the civilian world, an E-7 typically needs a civilian salary of $110,000–$135,000 with equivalent benefits — achievable, but often underestimated.",

"sgli-to-vgli-conversion-after-separation": "SGLI coverage ends 120 days after separation, and the VGLI conversion window — which requires no health exam — closes at 240 days post-separation. After Day 240, a medical exam is required to convert; after 1 year and 120 days, VGLI is no longer available at any price. VGLI premiums start low but escalate steeply with age — reaching $270/month by 50–54 — which is why purchasing competitive private term life insurance while still on active duty, before health issues develop, is generally the more cost-effective long-term strategy.",

"what-is-bah-military-housing-allowance": "BAH (Basic Allowance for Housing) is a monthly payment set by duty station ZIP code, pay grade, and dependency status — excluded from federal taxable income and designed to offset local housing costs for a member's grade and family situation. It is not based on where the member actually lives; it is based on where they are stationed. E-5 with-dependent BAH ranges from under $1,600/month at some installations to nearly $4,000/month at high-cost stations, which is why looking up the specific rate — not relying on averages — matters before making any housing decision.",

"how-military-retirement-works": "Military retirement pays an immediate monthly pension beginning the day a service member retires — typically around age 38–40 for a 20-year member — not a 401(k) balance drawn down at 65. Under High-3, retirement pay equals 2.5% multiplied by years of service multiplied by the average of the three highest-pay years, producing 50% of that average at exactly 20 years; under BRS, the multiplier is 2.0%, partially offset by government TSP matching of up to 5% of base pay during service. There is no partial vesting before 20 years under regular longevity retirement, making the military pension structurally different from virtually every civilian retirement plan.",

"deployment-financial-planning": "A combat zone deployment creates a narrow window of financial advantages that cannot be replicated in any other military or civilian context. The Combat Zone Tax Exclusion eliminates federal income tax on all enlisted base pay; Roth TSP contributions from that excluded pay carry a triple tax advantage — no tax going in, growing tax-free, and tax-free on qualified withdrawal; and the Savings Deposit Program pays a guaranteed 10% annual return on up to $10,000. An E-6 on a 9-month combat tour who uses all three tools can realistically accumulate $35,000–$50,000 in combined savings and investments during the deployment.",

"roth-tsp-deployment-strategy": "Combat zone Roth TSP contributions are structurally unique: they are made from income excluded from federal income tax under the Combat Zone Tax Exclusion, grow tax-free, and qualify for tax-free withdrawal in retirement — a triple tax advantage unavailable at any other point in a military or civilian career. A $20,000 Roth TSP contribution at age 25 from combat pay, growing at 7% annually, reaches approximately $214,000 by age 60 with no tax owed on qualified withdrawal. Two combat deployments where a member contributes near the $24,500 Roth elective deferral limit can build a significant tax-free retirement asset over a career.",

"are-you-financially-ready-to-leave-the-military": "Financial readiness for military separation requires three conditions: a positive monthly income surplus after replacing TRICARE healthcare, at least six months of liquid emergency savings, and a VA disability claim filed or in active process. Healthcare replacement is typically the most underestimated line item — TRICARE costs $0 on active duty, while comparable civilian family coverage commonly runs $525–$1,700/month in premiums alone. Running this calculation against post-separation income and actual costs — not military-side numbers — before accepting any civilian offer is the step most transitioning service members skip.",

"deployment-pay-explained": "Deployment to a qualifying combat zone adds several overlapping pay components: the Combat Zone Tax Exclusion eliminates federal income tax on all enlisted base pay; Hostile Fire/Imminent Danger Pay adds up to $225/month; Family Separation Allowance may add $300/month for qualifying members with dependents; and the Savings Deposit Program pays 10% guaranteed annual interest on up to $10,000. The total financial impact of a 12-month combat deployment varies by rank, family status, and how the benefits are used — but the window closes the moment the deployment ends, making advance planning essential.",

"skillbridge-program-guide": "SkillBridge is a DoD program allowing service members in their final 180 days of service to train at a civilian company while continuing to receive full military pay and benefits — base pay, BAH, BAS, and TRICARE unchanged. The financial value is not the training itself but the elimination of the unpaid job-search gap that typically follows separation, which is worth $15,000–$30,000 or more in avoided income loss depending on target salary. Commander approval is required and not guaranteed, so beginning the conversation 9–12 months before the anticipated separation date is essential.",

"how-to-read-military-les-2026": "Your Leave and Earnings Statement is your military pay stub — available every pay period at mypay.dfas.mil — and it is the authoritative record of base pay, allowances, taxes withheld, TSP contributions, and leave balance. The Entitlements section shows every dollar earned; the Deductions section shows every dollar taken out; and the Pay Entry Base Date (PEBD) determines your position on the pay chart, which must be correct for pay to be right. A single undetected error — wrong dependency status for BAH, TSP contribution below the matching threshold, state taxes withheld for the wrong state — can cost hundreds of dollars per month without a regular review.",

"military-tax-advantages": "Military compensation includes several tax exclusions that substantially increase its value compared to equivalent civilian wages. BAH and BAS are excluded from federal income tax, FICA, and most state income taxes — for an E-5 in San Diego, that is roughly $4,450/month excluded from taxable income, saving approximately $15,800 per year at a combined 22% federal rate. During combat zone months, all enlisted base pay is federally excluded as well, and Roth TSP contributions from that excluded pay carry a triple tax advantage: no tax going in, tax-free growth, and tax-free on qualified withdrawal in retirement.",

"tsp-fund-options-explained": "TSP offers five individual funds — G (government bonds), F (fixed-income index), C (S&P 500 equivalent), S (small-cap index), and I (international index) — plus Lifecycle funds that automatically blend them based on a target retirement date. New BRS enrollees default to an age-appropriate Lifecycle fund, which is a reasonable starting point. The most important thing to understand is the G Fund: it carries essentially no risk of loss but has historically earned modest returns that may barely keep pace with inflation, while the C Fund has significantly higher historical long-term average returns with more short-term volatility.",

"roth-tsp-advantage-junior-enlisted": "Junior enlisted are in the strongest possible position to benefit from Roth TSP: low marginal tax rates now mean paying minimal taxes on contributions, and decades of compound growth mean early contributions can outperform much larger contributions made later in a career. An E-3 likely pays 10–12% federal income tax on base pay — one of the lowest brackets in the tax code — making the Roth-vs-Traditional tradeoff strongly favor Roth. A $300/month Roth TSP contribution starting at age 20, growing at a 10% average annual return, grows to approximately $1.9 million by age 60 — and all qualified withdrawals are tax-free.",

"military-tax-advantages-by-state": "Your state of legal residence — not your current duty station — generally controls whether military base pay is subject to state income tax, because SCRA typically prevents the duty-station state from taxing military members solely on the basis of being stationed there. Nine states have no state income tax at all: Alaska, Florida, Nevada, New Hampshire, South Dakota, Tennessee, Texas, Washington, and Wyoming. For an E-6 earning approximately $57,000 in base pay, establishing legal residence in a no-income-tax state versus a 5% state saves approximately $2,800 per year — roughly $56,000 over a 20-year career.",

"tsp-for-beginners-what-happens-if-you-do-nothing": "Under BRS, the military automatically enrolls new members in TSP at 5% of basic pay, invested in an age-appropriate Lifecycle fund — a reasonable default that most members never examine. The government adds a 1% automatic contribution after 60 days and begins matching contributions up to 5% of base pay after two years of service, so contributing less than 5% means leaving part of that match on the table every month. The most consequential decision is fund allocation: an account sitting in the G Fund can produce significantly lower long-term growth than one diversified into stock funds, and the compounding difference over a 20-year career can reach hundreds of thousands of dollars.",

"how-to-read-your-les": "Your Leave and Earnings Statement is the authoritative record of military pay — 30+ line items covering base pay, allowances, federal and state taxes, SGLI, TSP contributions, and leave balance across six sections. BASE PAY is taxable; BAH and BAS are generally excluded from federal taxable income and FICA; CONUS COLA is taxable even though it is a military allowance. The most consequential errors — wrong BAH dependency status, TSP contribution below the matching threshold, state taxes withheld for the wrong state — are easy to miss without a monthly review and can cost hundreds of dollars per month if they go undetected.",

"tamp-healthcare-after-military-separation": "TAMP (Transitional Assistance Management Program) provides 180 days of premium-free TRICARE coverage after qualifying military separations — primarily involuntary separations and certain force-shaping events, not routine end-of-enlistment discharges. During the TAMP period, coverage extends to the service member and all eligible dependents enrolled in DEERS, with no enrollment premium. Day 181 is a hard cutoff with no grace period, which means planning the transition to the next coverage source must happen before Day 181, not after.",

"brs-vs-high-3-retirement": "The core difference between BRS and High-3 is the pension multiplier: 2.5% per year of service under High-3 versus 2.0% per year under BRS, producing 50% of High-3 base pay at 20 years versus 40% under BRS. BRS partially offsets the smaller pension with government TSP matching of up to 5% of base pay and continuation pay at 8–12 years of service. Service members who entered after January 1, 2018 are in BRS automatically; understanding which system you are in determines how the retirement math works and what breakeven assumptions apply.",

"your-first-military-paycheck-what-to-know": "Your first military paycheck is almost certainly smaller than expected, and the gap is usually explained by the LES — your Leave and Earnings Statement, available at myPay.dfas.mil. The most common surprises for new members are SGLI life insurance deducted at $26/month, federal taxes withheld on base pay, and the absence of BAH for junior enlisted living in the barracks. The most important action before the second paycheck is verifying the TSP contribution is set to at least 5% to capture the full government match under BRS — every month that match is missed is unrecoverable.",

"pcs-financial-planning-guide": "A PCS involves 8–10 separate financial entitlements — DLA, MALT mileage, per diem, TLE, household goods weight, and more — each with its own deadline, calculation method, and eligibility rules. Filing the travel voucher within 60 days of reporting, understanding PPM versus government move math, and timing a lease exit to avoid overlap can make a $3,000–$5,000 difference in the final financial outcome. Most of the money left on the table is not recoverable after the move has started — the planning window is before orders are cut.",

"how-bah-builds-wealth": "BAH is excluded from federal taxable income and pays the same whether you rent or own — so every dollar not spent on housing is yours to keep or invest. The wealth-building mechanism is the VA loan: redirecting BAH toward a mortgage with $0 down and no PMI turns an ongoing rental payment into a principal-building asset. After a PCS, that home can become a rental, allowing BAH at the new duty station to support a new mortgage while the prior property continues building equity.",

"va-home-loan-basics": "The VA home loan is one of the most valuable financial benefits military service provides — enabling eligible borrowers to purchase a primary residence with no down payment, no private mortgage insurance, and competitive interest rates. The loan comes from a private lender; the Department of Veterans Affairs guarantees a portion against default, which is what allows lenders to offer those terms. The benefit does not expire, can be used multiple times with entitlement restoration, and is available to active-duty members, veterans, qualifying Guard and Reserve members, and certain surviving spouses.",

"can-i-use-va-loan-again": "The VA loan benefit has no expiration date and no limit on the number of times it can be used — a service member can use it at every duty station over an entire career. Entitlement is restored in full when a home with a VA loan is sold and the balance is paid off, allowing the same $0-down, no-loan-limit benefit to be used again immediately. With sufficient remaining entitlement, two VA loans can be held simultaneously — a common scenario when PCSing before selling a previous home.",

"va-loan-funding-fee-explained": "The VA funding fee is the main VA-specific cost most non-exempt borrowers pay — a one-time charge to the Department of Veterans Affairs calculated as a percentage of the base loan amount. For a first-use purchase loan with no down payment, the fee is 2.15% — $7,525 on a $350,000 loan; subsequent-use borrowers pay 3.30%, or $11,550 on the same loan; and IRRRL refinances carry a much lower 0.50% fee. Veterans receiving VA disability compensation are commonly exempt from the fee entirely on every use, which is worth confirming on the Certificate of Eligibility before closing.",

"using-bah-to-buy-a-home": "BAH is excluded from federal taxable income and is commonly counted as qualifying income for a VA mortgage, meaning it can be applied toward a mortgage payment rather than rent. Whether redirecting BAH toward ownership makes financial sense depends on the specific duty station, expected tour length, and exit plan at PCS — at many moderate-cost installations, BAH is close to or above the estimated PITI on a median-priced local home financed with a VA loan, but the math varies significantly by market. The decision also needs to account for what happens when BAH ends: both BAH and base pay stop at separation, while the mortgage does not.",
}

results = []
skipped = []

for slug, para in paragraphs.items():
    fpath = os.path.join(BASE, f"{slug}.mdx")
    if not os.path.exists(fpath):
        print(f"FILE NOT FOUND: {slug}")
        continue

    with open(fpath, 'r', encoding='utf-8') as f:
        content = f.read()

    qa_pos = content.find('<QuickAnswer>')
    if qa_pos == -1:
        print(f"SKIP (no QuickAnswer): {slug}")
        skipped.append(slug)
        continue

    # Find end of frontmatter (second ---)
    first_fm = content.find('---')
    second_fm = content.find('---', first_fm + 3)
    fm_end = second_fm + 3 if second_fm != -1 else 0

    after_fm = content[fm_end:qa_pos].strip()
    if len(after_fm) > 20:
        print(f"SKIP (has content before QA): {slug} | content: {repr(after_fm[:60])}")
        skipped.append(slug)
        continue

    # Insert paragraph before <QuickAnswer>
    new_content = content[:qa_pos] + para + "\n\n" + content[qa_pos:]
    with open(fpath, 'w', encoding='utf-8') as f:
        f.write(new_content)

    first_sentence = para.split('.')[0] + '.'
    results.append((slug, first_sentence))
    print(f"DONE: {slug}")

print(f"\n=== PROCESSED: {len(results)} posts, SKIPPED: {len(skipped)} ===")
for slug, sentence in results:
    print(f'[{slug}] — "{sentence}"')
